import { Product } from "../model/prodcutModel";
import { User } from "../model/userModel";
import bcrypt from 'bcryptjs'

export const Products: Product[] = [
  {
    name: "Blue Metal",
    slug: "blue-Metal",
    brand: "nike",
    image: "/../images/b1.jpg",
    category: "shirt",
    price: 12,
    rating: 1,
    countInStock: 23,
    numReviews: 2,
    description: 'Briefs are snug-fitting, tight underwear that cover the waist and extend down the upper thigh. They offer full coverage and support for both men and women',
  },
  {
    name: "Graara Shub",
    slug: "gray-club",
    brand: "Calvin Klein",
    image: "/../images/b2.jpg",
    category: "shirt",
    price: 30,
    rating: 3,
    countInStock: 11,
    numReviews: 30,
    description: 'Boxers are loose-fitting shorts-style underwear that provide more freedom of movement. They usually have an elastic waistband and offer less support compared to briefs',
  },
  {
    name: "Victorias",
    slug: "victorias-secret",
    brand: "Victorias Secret",
    image: "/../images/b3.jpg",
    category: "shirt",
    price: 2.5,
    rating: 4.5,
    countInStock: 10,
    numReviews: 14,
    description: ' Victorias Secret is a popular brand specializing in womens lingerie and underwear. They are known for their feminine designs, including bras, panties, and sleepwear, often featuring lace, satin, and intricate detailing',
  },
  {
    name: "Jockey Black",
    slug: "jockey-black",
    brand: "Jockey",
    image: "/../images/b4.jpg",
    category: "shirt",
    price: 12,
    rating: 3,
    countInStock: 7,
    numReviews: 9,
    description: 'Bras are undergarments specifically designed to support and shape the breasts. They come in various styles, including padded, push-up, sports, and bralettes, catering to different needs and preferences',
  },
  {
    name: "Versace Log",
    slug: "versace",
    brand: "austalia",
    image: "/../images/c1.jpg",
    category: "pants",
    price: 12,
    rating: 5,
    countInStock: 0,
    numReviews: 39,
    description: 'Tommy Hilfiger is a fashion brand that offers a range of underwear for men and women. Their designs often feature their signature red, white, and blue logo and incorporate classic, sporty aesthetics',
  },
  {
    name: "Armani Jeans",
    slug: "armani",
    brand: "Kutub Utara",
    image: "/../images/c2.jpg",
    category: "pants",
    price: 15,
    rating: 5,
    countInStock: 12,
    numReviews: 39,
    description: 'Hanes is a trusted brand that offers comfortable and affordable underwear for both men and women. They provide a wide range of basic styles, including briefs, boxers, and panties, made from soft and breathable materials',
  },
  {
    name: "Balenciaga",
    slug: "balenciaga",
    brand: "sahara",
    image: "/../images/c3.jpg",
    category: "pants",
    price: 18,
    rating: 3.5,
    countInStock: 23,
    numReviews: 10,
    description: 'Boxers are loose-fitting shorts-style underwear that provide more freedom of movement. They usually have an elastic waistband and offer less support compared to briefs',
  },
  {
    name: "Puma Kate",
    slug: "mPuma",
    brand: "sahara",
    image: "/../images/c4.jpg",
    category: "pants",
    price: 18,
    rating: 2.3,
    countInStock: 17,
    numReviews: 10,
    description: 'Hanes is a trusted brand that offers comfortable and affordable underwear for both men and women. They provide a wide range of basic styles, including briefs, boxers, and panties, made from soft and breathable materials',
  },
];


export const Users: User[] = [
  {
    name: 'Joe',
    email: 'admin@gmail.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },
  {
    name: 'Jhon',
    email: 'user@gmail.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
]
